# Find box dimensions
This notebook shows how to calculate appropriate box dimensions for a water box.
### Set up environment

In [7]:
import mdtraj as md
import numpy as np

### Specify PDB file and size of box
Here we use 12 angstroms as the padding distance so the water box will extend 12 angstroms from the protein in each direction

In [ ]:
t = md.load('c3d_cr2_full_mini.pdb')
padding_dist = 12 #angstroms

### Initial protein dimensions calculations

In [9]:
max_coords = np.amax(t.xyz[0], axis=0)*10 #Multiplied by 10 to convert into angstroms
min_coords = np.amin(t.xyz[0], axis=0)*10 #Multiplied by 10 to convert into angstroms
box_dims = np.ceil(max_coords - min_coords)+(padding_dist*2)
cellOrigin = min_coords+((max_coords-min_coords)/2)

print(max_coords)
print(min_coords)
print(box_dims)
print(cellOrigin)

[ 13.74199963   4.95300007 -31.63399887]
[-44.36399841 -53.82099915 -87.37000275]
[ 83.  83.  80.]
[-15.31099892 -24.43400002 -59.5019989 ]


### Adjusted box dims and min/max calculations

In [10]:
max_coords_new = cellOrigin + (box_dims/2)
min_coords_new = cellOrigin - (box_dims/2)
box_dims_new = max_coords_new-min_coords_new
cellOrigin_new = min_coords_new+(box_dims_new/2)
print('Min: '+' '.join(map(str, min_coords_new)))
print('Max: '+' '.join(map(str, max_coords_new)))
print('CellOrigin: '+' '.join(map(str, cellOrigin_new)))
print('Box Dims: '+' '.join(map(str, box_dims_new)))

Min: -56.811 -65.934 -99.502
Max: 26.189 17.066 -19.502
CellOrigin: -15.311 -24.434 -59.502
Box Dims: 83.0 83.0 80.0


### NAMD-ready formatting

In [11]:
for i in np.arange(3):
        print('cellBasisVector{} {}'.format(i+1,' '.join(map(str, np.diag(box_dims_new)[i]))))
print('cellOrigin '+' '.join(map(str, cellOrigin_new)))

cellBasisVector1 83.0 0.0 0.0
cellBasisVector2 0.0 83.0 0.0
cellBasisVector3 0.0 0.0 80.0
cellOrigin -15.311 -24.434 -59.502
